version: 0.2

phases:
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
       - pwd
       - git log
       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo "post build"

